MCFC/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios import urls
from jogadores import urls as urls_jogadores
from jogos import urls as urls_jogos
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from usuarios.views import logout_view
from .views import IndexView, administrativo
from django.contrib.auth.decorators import login_required, user_passes_test


def is_admin(user):
    return user.groups.filter(name="administrativo").exists()


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include(urls)),
    path(
        "login/", LoginView.as_view(template_name="usuarios/login.html"), name="login"
    ),
    path("logout/", logout_view, name="logout"),
    path("jogadores/", include(urls_jogadores)),
    path("jogos/", include(urls_jogos)),
    path("", IndexView.as_view(), name="home"),
    path("administrativo/", administrativo, name="administrativo"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jogadores/urls.py
from django.urls import path
from .views import (
    JogadorListView,
    CreateJogadorView,
    UpdateJogadorView,
    DeleteJogadorView,
    DetailJogadorView,
)
from django.contrib.auth.decorators import login_required, user_passes_test


def is_admin(user):
    return user.groups.filter(name="administrativo").exists()


urlpatterns = [
    path("", JogadorListView.as_view(), name="jogadores"),
    path(
        "criar/",
        login_required(user_passes_test(is_admin)(CreateJogadorView.as_view())),
        name="cadastrar_jogador",
    ),
    path(
        "atualizar/<uuid:id>",
        login_required(user_passes_test(is_admin)(UpdateJogadorView.as_view())),
        name="atualizar_jogador",
    ),
    path("detalhes/<uuid:id>", DetailJogadorView.as_view(), name="detalhe_jogador"),
    path(
        "deletar/<uuid:id>",
        login_required(user_passes_test(is_admin)(DeleteJogadorView.as_view())),
        name="deletar_jogador",
    ),
]

jogadores/models.py
from django.db import models
from usuarios.models import NewUser
import uuid

# Create your models here.


class Jogador(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    jogador = models.OneToOneField(NewUser, on_delete=models.CASCADE)
    jogos = models.IntegerField(blank=True, null=True, default=None)
    gols = models.IntegerField(blank=True, null=True, default=None)
    assistencias = models.IntegerField(blank=True, null=True, default=None)
    clean_sheet = models.IntegerField(blank=True, null=True, default=None)
    mvp = models.IntegerField(blank=True, null=True, default=None)

    def __str__(self):
        return self.jogador.first_name

usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


import uuid

# Create your models here.


class NewUser(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(max_length=255, unique=True, blank=True, null=True)
    posicoes = (
        ("GK", "goleiro"),
        ("ZG", "zagueiro"),
        ("LD", "lateral direito"),
        ("LE", "lateral esquerdo"),
        ("VOL", "volante"),
        ("MEI", "meio-campista"),
        ("AT", "atacante"),
    )
    posicao = models.CharField(max_length=3, choices=posicoes, blank=False, null=False)
    descricao = models.TextField(blank=True, null=True)
    foto_perfil = models.ImageField(
        upload_to="fotos/", blank=True, null=True, default=None
    )

    def __str__(self):
        return self.username

    def get_jogador(self):
        """Retorna o jogador associado, se existir."""
        return getattr(self, "jogador", None)


class Invitation(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    token = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    email = models.EmailField(unique=True)
    used = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.email} - {'Usado' if self.used else 'Não usado'}"

jogadores/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView,
    UpdateView,
    CreateView,
    DeleteView,
    DetailView,
)
from .models import Jogador
from django.urls import reverse_lazy

# Create your views here.


class JogadorListView(ListView):
    model = Jogador
    template_name = "jogadores/jogadores.html"
    context_object_name = "jogadores"


class CreateJogadorView(CreateView):
    model = Jogador
    template_name = "jogadores/cadastrar_jogador.html"
    fields = "__all__"
    context_object_name = "cadastrar_jogador"
    success_url = reverse_lazy("jogadores")
    queryset = Jogador.objects.all()


class DetailJogadorView(DetailView):
    model = Jogador
    template_name = "jogadores/jogador.html"
    pk_url_kwarg = "id"
    context_object_name = "jogador"


class UpdateJogadorView(UpdateView):
    model = Jogador
    fields = "__all__"
    template_name = "jogadores/atualizar_jogador.html"
    context_object_name = "atualizar_jogador"
    pk_url_kwarg = "id"
    success_url = reverse_lazy("jogadores")


class DeleteJogadorView(DeleteView):
    model = Jogador
    template_name = "jogadores/delete_jogador.html"
    context_object_name = "deletar_jogador"
    pk_url_kwarg = "id"
    success_url = reverse_lazy("jogadores")

jogadores/templates/jogadores/atualizar_jogador.html
{% extends "base.html" %}
{% block content %}
<h1 class="ml-10 mt-10 text-black text-xl">{% if object %}Editar{% else %}Criar{% endif %} Jogador</h1>
<div class=" w-full h-auto">
  <form class="flex flex-col" method="post">
    {% csrf_token %}
    {% for field in form %}
      <label class="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b border-gray-300">
        {{field.label}}:
      </label>
      {{field}}
    {% endfor %}
    <button class="bg-red-500 cursor-pointer hover:underline" type="submit">Salvar</button>
  </form>
</div>
{% endblock %}

jogadores/templates/jogadores/cadastrar_jogador.html
{% extends "base.html" %}
{% block content %}
<h1 class="ml-10 mt-10 text-black text-xl">{% if object %}Editar{% else %}Criar{% endif %} Usuario</h1>
<div class=" w-full h-auto">
  <form class="flex flex-col" method="post">
    {% csrf_token %}
    {% for field in form %}
      <label class="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b border-gray-300">
        {{field.label}}:
      </label>
      {{field}}
    {% endfor %}
    <button class="bg-red-500 cursor-pointer hover:underline" type="submit">Salvar</button>
  </form>
</div>
{% endblock %}

jogadores/templates/jogadores/delete_jogador.html
{% extends "base.html" %}
{% block content %}
<div class="flex justify-center bg-gray-200 space-x-2">
  <h1 class="flex justify-center text-2xl">Excluir Jogador:</h1>
  <h1 class="flex justify-center text-2xl text-blue-800 ">{{ object.first_name }} {{ object.last_name }}</h1>
</div>
<h1 class="flex text-2xl mx-3">Informações do atleta:</h1>
<div class="border bg-gray-100 p-4 overflow-x-auto">
  <div class="min-w-full border border-gray-300 flex flex-col rounded-lg shadow">
    <div class="flex text-2xl text-red-600 m-2">
      <h2>Nome:</h2>
      <p class="mx-2">{{ object.jogador.first_name }}</p>
    </div>
    <div class="flex text-2xl text-red-600 m-2">
      <h2>Sobrenome:</h2>
      <p class="mx-2">{{ object.jogador.last_name }}</p>
    </div>
    <div class="flex text-2xl text-red-600 m-2">
      <h2>Email:</h2>
      <p class="mx-2">{{ object.jogador.email }}</p>
    </div>
    <div class="flex text-2xl text-red-600 m-2">
      <h2>Posição:</h2>
      <p class="mx-2">{{ object.jogador.get_posicao_display }}</p>
    </div>
    <div class="flex text-2xl text-red-600 m-2">
      <h2>Jogos:</h2>
      <p class="mx-2">{{ object.jogos}}</p>
    </div>
    <form method='POST'>
      {% csrf_token %}
      <button type="submit" class="hover:bg-red-700 hover:text-white text-red-600 rounded-sm">Excluir</button>
      <button class="hover:bg-red-700 hover:text-white text-red-600 rounded-sm"><a href="{% url "jogadores" %}">Cancelar</a></button>
    </form>
  </div>
</div>

{% endblock  %}

jogadores/templates/jogadores/jogador.html
{% extends "base.html" %}
{% block content %}
<div class="flex justify-center bg-gray-200 space-x-2">
  <h1 class="flex justify-center text-2xl">Jogador:</h1>
  <h1 class="flex justify-center text-2xl text-blue-800 ">{{ object.jogador.first_name }} {{ object.jogador.last_name }}</h1>
</div>
<h1 class="flex text-2xl mx-3">Informações do atleta:</h1>
<div class="border bg-gray-100 p-4 overflow-x-auto">
    {% if object.jogador.foto_perfil == '' %}
    <div class="m-2 border border-black w-20 h-28">

    </div>
    {% else %}
    <div class="m-2">
      <img class="w-20" src="{{ object.jogador.foto_perfil.url }}"></img>
    </div>
    {% endif %}
    <div class="flex text-2xl text-red-600 m-2">
      <h2>Nome:</h2>
      <p class="mx-2">{{ object.jogador.first_name }}</p>
    </div>
    <div class="flex text-2xl text-red-600 m-2">
      <h2>Sobrenome:</h2>
      <p class="mx-2">{{ object.jogador.last_name }}</p>
    </div>
    <div class="flex text-2xl text-red-600 m-2">
      <h2>Posição:</h2>
      <p class="mx-2">{{ object.jogador.get_posicao_display }}</p>
    </div>
    <div class="flex text-2xl text-red-600 m-2">
      <h2>Jogos:</h2>
      <p class="mx-2">{{ object.jogos }}</p>
    </div>
    <div class="flex text-2xl text-red-600 m-2">
      <h2>Gols:</h2>
      <p class="mx-2">{{ object.gols }}</p>
    </div>
      <div class="flex text-2xl text-red-600 m-2">
        <h2 class="">Assistencias:</h2>
        <p class="">{{ object.assistencias }}</p>
      </div>
      <div class="flex text-2xl text-red-600 m-2">
        <h2>Jogos sem tomar gol:</h2>
        <p class="mx-2">{{ object.clean_sheet }}</p>
      </div>
      <div class="flex text-2xl text-red-600 m-2">
        <h2>MVP:</h2>
        <p class="mx-2">{{ object.mvp }}</p>
      </div>
    
  </div>
</div>

{% endblock  %}

jogadores/templates/jogadores/jogadores.html
{% extends "base.html" %}
{% block content %}
<h1 class="flex justify-center text-2xl">Lista de Jogadores</h1>

  <div class="overflow-x-auto p-4 bg-gray-100" >
    <table class="min-w-full border border-gray-300 bg-white rounded-lg shadow">
      <thead class="bg-gray-200">
        <tr>
          <th class="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b border-gray-300">
            Nome
          </th>
          <th class="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b border-gray-300">
            Jogos
          </th>
          <th class="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b border-gray-300">
            Gols
          </th>
          <th class="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b border-gray-300">
            Assistencias
          </th>
          <th class="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b border-gray-300">
            Jogos sem tomar gol
          </th>
          <th class="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b border-gray-300">
            Mais informações
          </th>
          <th class="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b border-gray-300">
            Atualizar
          </th>
          <th class="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b border-gray-300">
            Excluir
          </th>
        </tr>
      </thead>
      {% for jogador in jogadores %}
      <tbody>
        <tr class="hover:bg-gray-100">
          <td class="px-4 py-2 text-sm text-gray-600 border-b border-gray-300">
            {{ jogador.jogador.first_name }}
          </td>
          <td class="px-4 py-2 text-sm text-gray-600 border-b border-gray-300">
            {{ jogador.jogos }}
          </td>
          <td class="px-4 py-2 text-sm text-gray-600 border-b border-gray-300">
            {{ jogador.gols }}
          </td>
          <td class="px-4 py-2 text-sm text-gray-600 border-b border-gray-300">
            {{ jogador.assistencias }}
          </td>
          <td class="px-4 py-2 text-sm text-gray-600 border-b border-gray-300">
            {{ jogador.clean_sheet }}
          </td>
          <td class="px-4 py-2 text-sm text-gray-600 border-b border-gray-300">
            <a 
              class="text-blue-500 hover:underline" 
              href="{% url 'detalhe_jogador' jogador.id %}">
              Info
            </a>
            <td class="px-4 py-2 text-sm text-gray-600 border-b border-gray-300">
              <a 
                class="text-blue-500 hover:underline" 
                href="{% url 'atualizar_jogador' jogador.id %}">
                Editar
              </a>
          </td>
          <td class="px-4 py-2 text-sm text-gray-600 border-b border-gray-300">
            <a 
              class="text-blue-500 hover:underline" 
              href="{% url 'deletar_jogador' jogador.id %}">
              Deletar
            </a>
        </td>
        </tr>
      </tbody>
      {% endfor %}
    </table>
  </div>
  
{% endblock %}